name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout icerpc/slicec
        uses: actions/checkout@v3
        with:
          repository: icerpc/slicec
          path: slicec

      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: icerpc-slice

      - name: Compile Slice files
        working-directory: slicec
        run: cargo run --release --bin slicec -- $(find ../icerpc-slice -name "*.slice") > /dev/null
